# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBrjaq6wqHby4A91eHraVZFFROKdO5gs
"""

class Skincare:
  def __init__(self,brand,price,quantity):
    self.brand=brand
    self.price=price
    self.quantity=quantity

  def display(self):
    print("brand:",self.brand)
    print("price:",self.price)
    print("quantity:",self.quantity)

  def update(self,price,quantity):
    self.price=price
    self.quantity=quantity

obj1=Skincare("Cetaphil",1200,50)
obj1.display()
obj1.update(1500,100)
obj1.display()

# prompt: example of multilevel inheritance

class Parent:
  def __init__(self,name):
    self.name=name

class Child(Parent):
  def __init__(self,name,age):
    super().__init__(name)
    self.age=age

class Grandchild(Child):
  def __init__(self,name,age,school):
    super().__init__(name,age)
    self.school=school

obj1=Grandchild("John",10,"ABC School")
print(obj1.name,obj1.age,obj1.school)

class bank:
  def __init__(self,name,acc_no,balance):
    self.name=name
    self.acc_no=acc_no
    self.balance=balance

  def deposit(self,amount):
    self.balance=self.balance+amount
    print("amount deposited")

  def withdraw(self,amount):
    if self.balance>=amount:
      self.balance=self.balance-amount
      print("amount withdrawn")
    else:
      print("insufficient balance")

  def display(self):
    print("name:",self.name)
    print("balance:",self.balance)

  def bankfees(self):
    print("bank fees:",self.balance*0.05)
    print("total:",self.balance*1.05)

obj1=bank("Sandra",80897865,10000)

obj1.deposit(5000)
obj1.withdraw(2000)
obj1.display()
obj1.bankfees()

